slice_name: Checkpoint-committed Kafka lag
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 6__table
  viz_type: echarts_timeseries_line
  time_range: No filter
  row_limit: 1000
  color_scheme: battleground
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: metric='committed_lag'
    clause: WHERE
  x_axis: sampled_at
  granularity_sqla: sampled_at
  time_grain_sqla: null
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(value)
    label: Checkpoint-committed Kafka lag
    optionName: Checkpoint-committed Kafka lag
  groupby: []
  show_legend: true
  rich_tooltip: true
  x_axis_time_format: '%H:%M:%S'
  y_axis_format: ',.2f'
  truncate_metric: true
  only_total: true
  show_value: false
  markerEnabled: true
query_context: null
cache_timeout: null
uuid: 1f36edf2-bfce-4b1d-84f9-09d1ffab23f8
version: 1.0.0
dataset_uuid: cd940999-2931-424f-887c-26b944183cc5
