slice_name: Completed eligible matches
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 2__table
  viz_type: big_number_total
  time_range: No filter
  row_limit: 1000
  color_scheme: battleground
  adhoc_filters: []
  metric:
    expressionType: SQL
    sqlExpression: COUNT(*) FILTER (WHERE status IN ('final','corrected'))
    label: Completed eligible matches
    optionName: Completed eligible matches
  y_axis_format: ',.0f'
query_context: null
cache_timeout: null
uuid: cbee7c1f-8d14-49e9-aa1c-5c4335e0969f
version: 1.0.0
dataset_uuid: 386042dd-7662-4845-9b0f-8537981dd42d
