slice_name: Running matches
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 2__table
  viz_type: big_number_total
  time_range: No filter
  row_limit: 1000
  color_scheme: battleground
  adhoc_filters: []
  metric:
    expressionType: SQL
    sqlExpression: COUNT(*) FILTER (WHERE status='running')
    label: Running matches
    optionName: Running matches
  y_axis_format: ',.0f'
query_context: null
cache_timeout: null
uuid: 59c81d3d-8629-4f7b-b67a-bb8921c14177
version: 1.0.0
dataset_uuid: 386042dd-7662-4845-9b0f-8537981dd42d
