slice_name: Winners
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  time_range: No filter
  row_limit: 1000
  color_scheme: battleground
  adhoc_filters: []
  metric:
    expressionType: SQL
    sqlExpression: SUM(wins)
    label: Winners
    optionName: Winners
  y_axis_format: ',.0f'
query_context: null
cache_timeout: null
uuid: d6633daa-74f9-4156-a731-5369579a2504
version: 1.0.0
dataset_uuid: f1390a11-3da6-445d-8207-007f529e2ec9
